export const RUTAS_LOADING = "RUTAS_LOADING";
export const ADD_RUTAS = "ADD_RUTAS";
export const RUTAS_FAILED = "RUTAS_FAILED";
export const SET_SCANNED = "SET_SCANNED";
export const SET_MODAL_VISIBLE = "SET_MODAL_VISIBLE";
export const SET_QR_DATA = "SET_QR_DATA";
export const FETCH_QR_INFO_SUCCESS = "FETCH_QR_INFO_SUCCESS";
export const FETCH_QR_INFO_FAILED = "FETCH_QR_INFO_FAILED";
